### PR TITLE
Added result dashboard

### PR DESCRIPTION
**Pull request by tombalu23**
Changed score from marks to percentage.

### CODE REVIEW

**Review by girish-cheedala — CHANGES_REQUESTED** [review]
add ui to result's page

**Comment by tombalu23** [comment]
> add ui to result's page

will be done

**Comment by girish-cheedala** [comment]
> > add ui to result's page
> 
> will be done

np

**Comment by tombalu23** [comment]
Added result dashboard. Please review the changes.

**Comment by girish-cheedala** [comment]
> Added result dashboard. Please review the changes.
output doesn't seem to be proper
output

have shared a screenshot
please fix it

**Comment by tombalu23** [comment]
Fixed the issue. Should work fine now.

> > Added result dashboard. Please review the changes.
> > output doesn't seem to be proper
> > output
> 
> have shared a screenshot
> please fix it

**Pull request merged**
